AIFF-C uncompressed support
umjammer/tritonus pull request #9
Opened 2024-02-11 21:13 UTC by CatsLover2006

Added support for AIFF-C compression types `twos` and `swot`. Neither actually contain compressed data. `twos` is quite literally the same as no compression at all, and `swot` is, as the name hints at, little endian, compared to `twos` and the default using big endian. Fixes AIFF-C files generated by iTunes, which use `swot` for some reason only known to Apple.
Also added `.DS_Store` to the `.gitignore` because macs suck like that.

2024-02-11 22:40 UTC, umjammer requested changes

2024-02-11 22:40 UTC, umjammer commented on tritonus-remaining/src/main/java/org/tritonus/sampled/file/AiffAudioFileReader.java
> +                nSampleSize > 8 && !isLittleEndian);
it seems adding endianness so easily.
please add test cases that prove specs so far is working w/ new code.

2024-02-12 20:39 UTC, CatsLover2006 reviewed
Added a test case for little-endian AIFF

2024-02-12 21:43 UTC, umjammer approved these changes
lgtm

2024-02-12 21:50 UTC, merged